name: Declarative Automation Bundles

on:
  workflow_dispatch:
    inputs:
      upload_config:
        description: 'Upload config files to Databricks Volume?'
        required: true
        type: boolean
        default: false  # ✅ Won't upload unless you check the box

permissions:
  contents: read

defaults:
  run:
    working-directory: .

jobs:
#==========================================================================
# JOB: Validate Declarative Automation Bundles
#==========================================================================
  validate:
    name: Validate declarative automation bundles
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: 2118cc40-71a3-4e53-92ca-a60f61806747
      ARM_CLIENT_SECRET: _Nv8Q~yj2E4mv8vVjORdRtgdpPxJPuXS2vep5b1P
      ARM_TENANT_ID: 8d970696-f884-42b5-a8ea-742bf9d0d576
      DATABRICKS_HOST: https://adb-7405607349730837.17.azuredatabricks.net/
    continue-on-error: false
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Ensure .py files are Databricks notebooks
        run: |
          Get-ChildItem -Path "${{ github.workspace }}" -Filter "*.py" -Recurse | ForEach-Object {
            ("# Databricks notebook source`n" + (Get-Content $_.FullName -Raw)) | Set-Content $_.FullName
          }
        shell: pwsh

      - name: Create databricks.yml
        run: |
          cat <<'EOF' > databricks.yml
          bundle:
            name: pharma_dabs

          include:
            - dbx/*.yml
            - dbx/*/*.yml

          sync:
            exclude:
              - ".github"
              - "databricks.yml"
            variables:
              catalog:
                description: "Catalog where volume and tables will be configured"
                default: sparktest_bill_catalog
              schema:
                description: "Schema where volume and tables will be configured"
                default: bill
              volume_name:
                description: "Name of volume"
                default: cost
              bronze_table_name:
                description: "Name of bronze table"
                default: actuals_bronze
              silver_table_name:
                description: "Name of silver table"
                default: actuals_silver
              gold_table_name:
                description: "Name of gold table"  
                default: actuals_gold
              volume_path:
                default: /Volumes/${var.catalog}/${var.schema}/${var.volume_name}/
              source_file_path:
                description: "Location in Volume where AutoLoader is reading Cost Export files from"
                default: ${var.volume_path}/*/*/*/*.parquet
              billing_period_depth:
                description: "Pipeline uses split_part to extract billing period (e.g. 20250901-20250930) from file source_file_path"
                default: 7    
              ingestion_date_depth:
                description: "Pipeline uses split_part to extract ingestion date (e.g. 202509081628) from file source_file_path"  
                default: 8
              warehouse_id:
                description: "f30ef5b04d396f73"

          targets:
            dev:
              mode: development
              default: true
              workspace:
                host: https://adb-7405607349730837.17.azuredatabricks.net/
                root_path: ~/Workspace/Shared/DABS/
              permissions:
                - user_name: sce21cs004@sairamtap.edu.in
                  level: CAN_MANAGE

            prod:
              mode: production
              workspace:
                host: https://adb-7405607349730837.17.azuredatabricks.net/
                root_path: /Workspace/Shared/DABS/
              permissions:
                - user_name: sce21cs048@sairamtap.edu.in
                  level: CAN_MANAGE
          EOF

      - name: Validate bundle
        run: databricks bundle validate -t prod

#==========================================================================
# JOB: Deploy Declarative Automation Bundles
#==========================================================================
  deploy:
    name: Deploy declarative automation bundles
    if: ${{ needs.validate.result == 'success' }}
    needs: validate
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Ensure .py files are Databricks notebooks
        run: |
          Get-ChildItem -Path "${{ github.workspace }}" -Filter "*.py" -Recurse | ForEach-Object {
            ("# Databricks notebook source`n" + (Get-Content $_.FullName -Raw)) | Set-Content $_.FullName
          }
        shell: pwsh

      - name: Create databricks.yml
        run: |
          cat <<'EOF' > databricks.yml
          bundle:
            name: pharma_dabs

          include:
            - dbx/*.yml
            - dbx/*/*.yml

          sync:
            exclude:
              - ".github"
              - "databricks.yml"

            variables:
              catalog:
                description: "Catalog where volume and tables will be configured"
                default: sparktest_bill_catalog
              schema:
                description: "Schema where volume and tables will be configured"
                default: bill
              volume_name:
                description: "Name of volume"
                default: cost
              bronze_table_name:
                description: "Name of bronze table"
                default: actuals_bronze
              silver_table_name:
                description: "Name of silver table"
                default: actuals_silver
              gold_table_name:
                description: "Name of gold table"  
                default: actuals_gold
              volume_path:
                default: /Volumes/${var.catalog}/${var.schema}/${var.volume_name}/
              source_file_path:
                description: "Location in Volume where AutoLoader is reading Cost Export files from"
                default: ${var.volume_path}/*/*/*/*.parquet
              billing_period_depth:
                description: "Pipeline uses split_part to extract billing period (e.g. 20250901-20250930) from file source_file_path"
                default: 7    
              ingestion_date_depth:
                description: "Pipeline uses split_part to extract ingestion date (e.g. 202509081628) from file source_file_path"  
                default: 8
              warehouse_id:
                description: "f30ef5b04d396f73"


          targets:
            dev:
              mode: development
              default: true
              workspace:
                host: https://adb-7405607349730837.17.azuredatabricks.net/
                root_path: ~/Workspace/Shared/DABS/
              permissions:
                - user_name: sce21cs004@sairamtap.edu.in
                  level: CAN_MANAGE

            prod:
              mode: production
              workspace:
                host: https://adb-7405607349730837.17.azuredatabricks.net/
                root_path: /Workspace/Shared/DABS/
              permissions:
                - user_name: sce21cs048@sairamtap.edu.in
                  level: CAN_MANAGE
          EOF

      # ✅ Only runs if checkbox is checked
      - name: Delete existing config files
        if: ${{ inputs.upload_config == true }}
        run: databricks fs rm dbfs:/Volumes/sparktest_dev_catalog/dlt/config/ --recursive
        env:
          ARM_CLIENT_ID: 2118cc40-71a3-4e53-92ca-a60f61806747
          ARM_CLIENT_SECRET: _Nv8Q~yj2E4mv8vVjORdRtgdpPxJPuXS2vep5b1P
          ARM_TENANT_ID: 8d970696-f884-42b5-a8ea-742bf9d0d576
          DATABRICKS_HOST: https://adb-7405607349730837.17.azuredatabricks.net/

      # ✅ Only runs if checkbox is checked
      - name: Upload config files to Databricks Volume
        if: ${{ inputs.upload_config == true }}
        run: databricks fs cp ./config dbfs:/Volumes/sparktest_dev_catalog/dlt/config/ --recursive
        env:
          ARM_CLIENT_ID: 2118cc40-71a3-4e53-92ca-a60f61806747
          ARM_CLIENT_SECRET: _Nv8Q~yj2E4mv8vVjORdRtgdpPxJPuXS2vep5b1P
          ARM_TENANT_ID: 8d970696-f884-42b5-a8ea-742bf9d0d576
          DATABRICKS_HOST: https://adb-7405607349730837.17.azuredatabricks.net/

      # ✅ Only runs if checkbox is checked
      - name: Verify uploaded files in Databricks Volume
        if: ${{ inputs.upload_config == true }}
        run: databricks fs ls dbfs:/Volumes/sparktest_dev_catalog/dlt/config/ -l
        env:
          ARM_CLIENT_ID: 2118cc40-71a3-4e53-92ca-a60f61806747
          ARM_CLIENT_SECRET: _Nv8Q~yj2E4mv8vVjORdRtgdpPxJPuXS2vep5b1P
          ARM_TENANT_ID: 8d970696-f884-42b5-a8ea-742bf9d0d576
          DATABRICKS_HOST: https://adb-7405607349730837.17.azuredatabricks.net/

      - name: Deploy bundle
        run: databricks bundle deploy -t prod
        env:
          ARM_CLIENT_ID: 2118cc40-71a3-4e53-92ca-a60f61806747
          ARM_CLIENT_SECRET: _Nv8Q~yj2E4mv8vVjORdRtgdpPxJPuXS2vep5b1P
          ARM_TENANT_ID: 8d970696-f884-42b5-a8ea-742bf9d0d576
          DATABRICKS_HOST: https://adb-7405607349730837.17.azuredatabricks.net/





# name: Declarative Automation Bundles  # name of the workflow
 
# on: 
#   workflow_dispatch: # manually run this pipeline ( workflow )
 
# permissions: # permissions for actions
#   contents: read # for actions/checkout
 
# defaults:
#   run:
#     working-directory: . # default working directory for all run steps ( . root directory of repo )
# jobs:
# #==========================================================================
# # JOB: Validate Declarative Automation Bundles
# #==========================================================================  
#   validate: # JOB ID
#     name: Validate declarative automation bundles # JOB NAME
#     runs-on: ubuntu-latest # runner used in the job
#     env:
#       ARM_CLIENT_ID: 2118cc40-71a3-4e53-92ca-a60f61806747     
#       ARM_CLIENT_SECRET: _Nv8Q~yj2E4mv8vVjORdRtgdpPxJPuXS2vep5b1P
#       ARM_TENANT_ID: 8d970696-f884-42b5-a8ea-742bf9d0d576
#       DATABRICKS_HOST: https://adb-7405607349730837.17.azuredatabricks.net/  

#     continue-on-error: false # if job fails, stop the workflow
#     steps:
 
#       # pull code from repo to runner ( )
#       - name: Checkout code # pull code from repo to runner ( )
#         uses: actions/checkout@v4.2.2
 
#       # install databricks cli  
#       - name: Setup Databricks CLI
#         uses: databricks/setup-cli@main
        
#       - name: Ensure .py files are Databricks notebooks (ubantu-latest)
#         run: |
#           Get-ChildItem -Path "${{ github.workspace }}" -Filter "*.py" -Recurse | ForEach-Object {
#             ("# Databricks notebook source`n" + (Get-Content $_.FullName -Raw)) | Set-Content $_.FullName
#           }
#         shell: pwsh

#       - name: Create databricks.yml
#         run: |
#           cat <<EOF > databricks.yml
#           bundle:
#             name: pharma_dabs

#           include:
#             - dbx/*.yml
#             - dbx/*/*.yml

#           sync:
#             exclude:
#               - ".github"    
#               - "databricks.yml"

#           targets:
#             dev:
#               mode: development
#               default: true
#               workspace:
#                 host: https://adb-7405607349730837.17.azuredatabricks.net/
#                 root_path: /Workspace/Shared/DABS/
#               permissions:
#                 - user_name: sce21cs004@sairamtap.edu.in
#                   level: CAN_MANAGE

#             prod:
#               mode: production
#               workspace:
#                 host: https://adb-7405607349730837.17.azuredatabricks.net/
#                 root_path: ~/Workspace/Shared/DABS/
#               permissions:
#                 - user_name: sce21cs048@sairamtap.edu.in
#                   level: CAN_MANAGE
#                 # - service_principal_name: 2118cc40-71a3-4e53-92ca-a60f61806747
#                 #   level: CAN_MANAGE
#           EOF

#       # validate Declarative Automation Bundles
#       - name: Validate bundle
#         run: databricks bundle validate -t prod
#         env:
#           ARM_CLIENT_ID: 2118cc40-71a3-4e53-92ca-a60f61806747     
#           ARM_CLIENT_SECRET: _Nv8Q~yj2E4mv8vVjORdRtgdpPxJPuXS2vep5b1P
#           ARM_TENANT_ID: 8d970696-f884-42b5-a8ea-742bf9d0d576
#           DATABRICKS_HOST: https://adb-7405607349730837.17.azuredatabricks.net/   
# #==========================================================================
# # JOB: Deploy Declarative Automation Bundles
# #==========================================================================  
#   deploy: # JOB ID
#     name: Deploy declarative automation bundles # JOB NAME
#     if: ${{ needs.validate.result == 'success' }}
#     needs: validate # this job depends on validate job
#     runs-on: ubuntu-latest # runner used in the job
#     continue-on-error: false # if job fails, stop the workflow
#     steps:
 
#       # pull code from repo to runner ( )
#       - name: Checkout code # pull code from repo to runner ( )
#         uses: actions/checkout@v4.2.2
 
#       # install databricks cli  
#       - name: Setup Databricks CLI
#         uses: databricks/setup-cli@main
        
#       - name: Ensure .py files are Databricks notebooks (ubantu-latest)
#         run: |
#           Get-ChildItem -Path "${{ github.workspace }}" -Filter "*.py" -Recurse | ForEach-Object {
#             ("# Databricks notebook source`n" + (Get-Content $_.FullName -Raw)) | Set-Content $_.FullName
#           }
#         shell: pwsh
#       # validate Declarative Automation Bundles
#       - name: Create databricks.yml
#         run: |
#           cat <<EOF > databricks.yml
#           bundle:
#             name: pharma_dabs

#           include:
#             - dbx/*.yml
#             - dbx/*/*.yml

#           sync:
#             exclude:
#               - ".github"    
#               - "databricks.yml"

#           targets:
#             dev:
#               mode: development
#               default: true
#               workspace:
#                 host: https://adb-7405607349730837.17.azuredatabricks.net/
#                 root_path: ~/Workspace/Shared/DABS/
#               permissions:
#                 - user_name: sce21cs004@sairamtap.edu.in
#                   level: CAN_MANAGE

#             prod:
#               mode: production
#               workspace:
#                 host: https://adb-7405607349730837.17.azuredatabricks.net/
#                 root_path: /Workspace/Shared/DABS/
#               permissions:
#                 - user_name: sce21cs048@sairamtap.edu.in
#                   level: CAN_MANAGE
#                 # - service_principal_name: 2118cc40-71a3-4e53-92ca-a60f61806747
#                 #   level: CAN_MANAGE
#           EOF

#       - name: Preparing the config file for deployment
#         run: databricks fs rm dbfs:/Volumes/sparktest_dev_catalog/dlt/config/ --recursive
#         env:
#           # BUNDLE_VAR_DATABRICKS_CLIENT_ID: 2118cc40-71a3-4e53-92ca-a60f61806747
#           ARM_CLIENT_ID: 2118cc40-71a3-4e53-92ca-a60f61806747     
#           ARM_CLIENT_SECRET: _Nv8Q~yj2E4mv8vVjORdRtgdpPxJPuXS2vep5b1P
#           ARM_TENANT_ID: 8d970696-f884-42b5-a8ea-742bf9d0d576
#           DATABRICKS_HOST: https://adb-7405607349730837.17.azuredatabricks.net/

#       - name: Deploy config file to databricks volume
#         run: databricks fs cp ./config dbfs:/Volumes/sparktest_dev_catalog/dlt/config/ --recursive
#         env:
#           # BUNDLE_VAR_DATABRICKS_CLIENT_ID: 2118cc40-71a3-4e53-92ca-a60f61806747
#           ARM_CLIENT_ID: 2118cc40-71a3-4e53-92ca-a60f61806747     
#           ARM_CLIENT_SECRET: _Nv8Q~yj2E4mv8vVjORdRtgdpPxJPuXS2vep5b1P
#           ARM_TENANT_ID: 8d970696-f884-42b5-a8ea-742bf9d0d576
#           DATABRICKS_HOST: https://adb-7405607349730837.17.azuredatabricks.net/

#       - name: Deploy bundle
#         run: databricks bundle deploy-t prod
#         env:
#           # BUNDLE_VAR_DATABRICKS_CLIENT_ID: 2118cc40-71a3-4e53-92ca-a60f61806747
#           ARM_CLIENT_ID: 2118cc40-71a3-4e53-92ca-a60f61806747     
#           ARM_CLIENT_SECRET: _Nv8Q~yj2E4mv8vVjORdRtgdpPxJPuXS2vep5b1P
#           ARM_TENANT_ID: 8d970696-f884-42b5-a8ea-742bf9d0d576
#           DATABRICKS_HOST: https://adb-7405607349730837.17.azuredatabricks.net/  

#       - name: Verify uploaded files in Databricks Volume
#         run: databricks fs ls dbfs:/Volumes/sparktest_dev_catalog/dlt/config/ -l
#         env:
#           # BUNDLE_VAR_DATABRICKS_CLIENT_ID: 2118cc40-71a3-4e53-92ca-a60f61806747
#           ARM_CLIENT_ID: 2118cc40-71a3-4e53-92ca-a60f61806747
#           ARM_CLIENT_SECRET: _Nv8Q~yj2E4mv8vVjORdRtgdpPxJPuXS2vep5b1P
#           ARM_TENANT_ID: 8d970696-f884-42b5-a8ea-742bf9d0d576
#           DATABRICKS_HOST: https://adb-7405607349730837.17.azuredatabricks.net/